module.exports ={
    HOMEPAGE: '/',
    LOGIN: '/login',
    SIGNUP: '/signup',
    BLOG: '/blog',
    BASEURL: 'http://localhost:9000',
    POST: 'POST',
    GET: 'GET',
    USER: '/user',
    LIKE: '/like',
    COMMENT: '/comment',
    BOOKMARK: '/bookmark',    
    LIKEDPOSTS: '/likedPosts',
    BOOKMARKEDBLOGS:'/bookmarkedPosts',
    USER: '/user',
    FOLLOW: '/follow',
    FOLLOWERS: '/followers',
    FOLLOWEDUSERS: '/followedUsers',

}